In [2]:
import os
import numpy as np
from matplotlib import pyplot
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
%matplotlib inline

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
training_data_x = pd.read_excel("/content/Final dataset Attrition.xlsx", engine ="openpyxl")
training_data_x.head()

Age Attrition BusinessTravel              Department  DistanceFromHome  \
0   37       Yes  Travel_Rarely  Research & Development                 2   
1   21        No  Travel_Rarely  Research & Development                15   
2   45        No  Travel_Rarely  Research & Development                 6   
3   23        No  Travel_Rarely                   Sales                 2   
4   22        No  Travel_Rarely  Research & Development                15   

   Gender  JobInvolvement  JobLevel                JobRole  JobSatisfaction  \
0    Male               2         1  Laboratory Technician                3   
1    Male               3         1     Research Scientist                4   
2    Male               3         3      Research Director                1   
3    Male               3         1   Sales Representative                1   
4  Female               3         1  Laboratory Technician                4   

   ... Higher_Education  Date_of_Hire  Date_of_termination  \
0  ...       Graduation    2021-01-21                  NaN   
1  ...       Graduation    2021-03-13                  NaN   
2  ...  Post-Graduation    2021-01-23                  NaN   
3  ...              PHD    2021-04-25                  NaN   
4  ...              PHD    2021-06-14                  NaN   

    Status_of_leaving  Mode_of_work  Leaves  Absenteeism  Work_accident  \
0              Salary        OFFICE       4            2             No   
1       Work Accident           WFH       5            2             No   
2           Dept.Head           WFH       1            3             No   
3       Work Accident        OFFICE       1            0            Yes   
4  Better Opportunity           WFH       5            2             No   

   Source_of_Hire   Job_mode  
0       Job Event   Contract  
1       Recruiter  Part Time  
2       Job Event   Contract  
3       Recruiter   FullTime  
4       Job Event   Contract  

[5 rows x 32 columns]

# New Section

# **Notes about data**

We need to perform one-hot-encoding on some of the input features that are string-like and add them at the end of the training set. We may ignore the day of joining feature since the data about leaving is not provided and it would be trivial to have a single date as going by intuition it should have zero impact on the attrition rate.

**Features to be changed:** 


*   BusinessTravel
*   Department
*   Gender
*   JobRole
*   MaritalStatus
*   OverTime


# **Scaling Integer features**

In [17]:
x_age = training_data_x['Age'].to_numpy()
x_distanceFromHome = training_data_x['DistanceFromHome'].to_numpy()
x_jobInvolvement = training_data_x['JobInvolvement'].to_numpy()
x_jobLevel = training_data_x['JobLevel'].to_numpy()
x_jobSatisfaction = training_data_x['JobSatisfaction'].to_numpy()
x_monthlyIncome = training_data_x['MonthlyIncome'].to_numpy()
x_numCompaniesWorked = training_data_x['NumCompaniesWorked'].to_numpy()
x_percentSalaryHike = training_data_x['PercentSalaryHike'].to_numpy()
x_performanceRating = training_data_x['PerformanceRating'].to_numpy()
x_stockOptionLevel = training_data_x['StockOptionLevel'].to_numpy()
x_totalWorkingYears = training_data_x['TotalWorkingYears'].to_numpy()
x_trainingTimesLastYear = training_data_x['TrainingTimesLastYear'].to_numpy()
x_yearsAtCompany = training_data_x['YearsAtCompany'].to_numpy()
x_yearsSinceLastPromotion = training_data_x['YearsSinceLastPromotion'].to_numpy()
x_yearsWithCurrManager = training_data_x['YearsWithCurrManager'].to_numpy()
x_leaves = training_data_x['Leaves'].to_numpy()
x_absenteeism = training_data_x['Absenteeism'].to_numpy()

In [48]:
attrition = training_data_x['Attrition'].to_numpy()
attritionBoolean = []
for x in attrition:
  if(x == "Yes"):
    attritionBoolean.append(1)
  else:
    attritionBoolean.append(0)
attritionBoolean = np.array(attritionBoolean)
print(attritionBoolean)

[1 0 0 ... 0 0 1]


In [49]:
scalingFeatures = np.array(attritionBoolean)
scalingFeatures = np.vstack([scalingFeatures, x_age, x_distanceFromHome, x_jobInvolvement, x_jobLevel, x_jobSatisfaction, x_monthlyIncome, 
                             x_numCompaniesWorked, x_percentSalaryHike, x_performanceRating, x_stockOptionLevel, x_totalWorkingYears, 
                             x_trainingTimesLastYear, x_yearsAtCompany, x_yearsSinceLastPromotion, x_yearsWithCurrManager, x_leaves, 
                             x_absenteeism])
scalingFeatures = scalingFeatures.transpose()
print(scalingFeatures)

[[ 1 37  2 ...  0  4  2]
 [ 0 21 15 ...  0  5  2]
 [ 0 45  6 ...  0  1  3]
 ...
 [ 0 55 26 ... 13  2  1]
 [ 0 58 10 ...  8  2  2]
 [ 1 58 23 ...  6  4  3]]


# **Features to be split through one hot encoding**

In [50]:
x_workAccident = training_data_x['Work_accident'].to_numpy()
x_businessTravel = training_data_x['BusinessTravel'].to_numpy()
x_department = training_data_x['Department'].to_numpy()
x_gender = training_data_x['Gender'].to_numpy()
x_jobRole = training_data_x['JobRole'].to_numpy()
x_maritalStatus = training_data_x['MaritalStatus'].to_numpy()
x_overtime = training_data_x['OverTime'].to_numpy()
x_higherEducation = training_data_x['Higher_Education'].to_numpy()
x_statusOfLeaving = training_data_x['Status_of_leaving'].to_numpy()
x_modeOfWork = training_data_x['Mode_of_work'].to_numpy()
x_sourceOfHire = training_data_x['Source_of_Hire'].to_numpy()
x_jobMode = training_data_x['Job_mode'].to_numpy()

In [51]:
stringFeatures = np.array(x_workAccident)
stringFeatures = np.vstack([stringFeatures, x_businessTravel, x_department, x_gender, x_jobRole, x_maritalStatus, x_overtime, x_higherEducation,
                            x_statusOfLeaving, x_modeOfWork, x_sourceOfHire, x_jobMode])
stringFeatures = stringFeatures.transpose()
print(stringFeatures)


[['No' 'Travel_Rarely' 'Research & Development' ... 'OFFICE' 'Job Event'
  'Contract']
 ['No' 'Travel_Rarely' 'Research & Development' ... 'WFH' 'Recruiter'
  'Part Time']
 ['No' 'Travel_Rarely' 'Research & Development' ... 'WFH' 'Job Event'
  'Contract']
 ...
 ['No' 'Travel_Rarely' 'Sales' ... 'OFFICE' 'Recruiter' 'Part Time']
 ['Yes' 'Travel_Rarely' 'Sales' ... 'WFH' 'Job Event' 'Part Time']
 ['Yes' 'Travel_Rarely' 'Research & Development' ... 'WFH' 'Job Portal'
  'FullTime']]


In [52]:
featureEncoder = OneHotEncoder(handle_unknown = 'ignore')
featureEncoder.fit(stringFeatures)
featureEncoder.categories_

[array(['No', 'Yes'], dtype=object),
 array(['Non-Travel', 'Travel_Frequently', 'Travel_Rarely'], dtype=object),
 array(['Human Resources', 'Research & Development', 'Sales'], dtype=object),
 array(['Female', 'Male'], dtype=object),
 array(['Healthcare Representative', 'Human Resources',
        'Laboratory Technician', 'Manager', 'Manufacturing Director',
        'Research Director', 'Research Scientist', 'Sales Executive',
        'Sales Representative'], dtype=object),
 array(['Divorced', 'Married', 'Single'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['12th', 'Graduation', 'PHD', 'Post-Graduation'], dtype=object),
 array(['Better Opportunity', 'Dept.Head', 'Salary', 'Work Accident',
        'Work Environment'], dtype=object),
 array(['OFFICE', 'WFH'], dtype=object),
 array(['Job Event', 'Job Portal', 'Recruiter', 'Walk-in'], dtype=object),
 array(['Contract', 'FullTime', 'Part Time'], dtype=object)]

In [53]:
featureEncoder.get_feature_names_out(['workAccident', 
                                      'businessTravel',
                                      'department',
                                      'gender',
                                      'jobRole',
                                      'maritalStatus',
                                      'overtime',
                                      'higherEducation',
                                      'statusOfLeaving',
                                      'modeOfWork',
                                      'sourceOfHire',
                                      'jobMode'])

array(['workAccident_No', 'workAccident_Yes', 'businessTravel_Non-Travel',
       'businessTravel_Travel_Frequently', 'businessTravel_Travel_Rarely',
       'department_Human Resources', 'department_Research & Development',
       'department_Sales', 'gender_Female', 'gender_Male',
       'jobRole_Healthcare Representative', 'jobRole_Human Resources',
       'jobRole_Laboratory Technician', 'jobRole_Manager',
       'jobRole_Manufacturing Director', 'jobRole_Research Director',
       'jobRole_Research Scientist', 'jobRole_Sales Executive',
       'jobRole_Sales Representative', 'maritalStatus_Divorced',
       'maritalStatus_Married', 'maritalStatus_Single', 'overtime_No',
       'overtime_Yes', 'higherEducation_12th',
       'higherEducation_Graduation', 'higherEducation_PHD',
       'higherEducation_Post-Graduation',
       'statusOfLeaving_Better Opportunity', 'statusOfLeaving_Dept.Head',
       'statusOfLeaving_Salary', 'statusOfLeaving_Work Accident',
       'statusOfLeaving_Work

In [54]:
finalStringFeatures = featureEncoder.transform(stringFeatures).toarray()
print(finalStringFeatures)

[[1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]]


In [55]:
finalData = np.concatenate((scalingFeatures, finalStringFeatures), axis = 1)
print(finalData)

[[ 1. 37.  2. ...  1.  0.  0.]
 [ 0. 21. 15. ...  0.  0.  1.]
 [ 0. 45.  6. ...  1.  0.  0.]
 ...
 [ 0. 55. 26. ...  0.  0.  1.]
 [ 0. 58. 10. ...  0.  0.  1.]
 [ 1. 58. 23. ...  0.  1.  0.]]


# **Schema for the final Data**
y(attritionBoolean),

x_age, 

x_distanceFromHome, 

x_jobInvolvement, 

x_jobLevel, 

x_jobSatisfaction, 

x_monthlyIncome, 

x_numCompaniesWorked,

x_percentSalaryHike, 

x_performanceRating, 

x_stockOptionLevel, 

x_totalWorkingYears, 

x_trainingTimesLastYear,

x_yearsAtCompany, 

x_yearsSinceLastPromotion, 

x_yearsWithCurrManager, 

x_leaves, 

x_absenteeism

Rest of string features encoded



****


**We now split the data into two parts the first 1000 entries for training and the remaining as test data to test our model's accuracy.**

In [45]:
trainData = finalData[:1000]
testData = finalData[1000:]